from tkinter import *
  
root = Tk()
frame = Frame(root)
frame.pack()
bottomframe = Frame(root)
bottomframe.pack( side = BOTTOM )
redbutton = Button(frame, text = 'Red', fg ='red', command=lambda:print("Red Clicked"))
redbutton.pack( side = LEFT)
greenbutton = Button(frame, text = 'Brown', fg='brown', command=lambda:print("Brown Clicked"))
greenbutton.pack( side = LEFT )
bluebutton = Button(frame, text ='Blue', fg ='blue', command=lambda:print("Blue Clicked"))
bluebutton.pack( side = LEFT )
blackbutton = Button(bottomframe, text ='Black', fg ='black', command=lambda:print("Black Clicked"))
blackbutton.pack( side = BOTTOM)
root.mainloop()